spring:
  application:
    name: myApp
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/application_prod
    username: app_prod
    password: app_prod
    driver-class-name: org.postgresql.Driver

  security:
    user:
      roles: ROLE_ADMIN, ROLE_USER
      name: admin
      password: admin

#logging:
#  level:
#    org.springframework.web: ERROR
#    org.hibernate: INFO
#    org.hibernate.SQL: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: INFO
